### ISSUE TITLE
Cannot set up react-cognito with non-default policy

### ISSUE THREAD

**Issue by kbrown** [isotoma/react-cognito#18]
Suppose I don't require email verification.

/**
 * sets up react-cognito with default policies.
*/
const setupCognito = (store, config) => {
  store.dispatch(Action.configure(config));
  enable(store, emailVerificationRequired);
  enable(store, identityPoolLogin);
};

How am I supposed to set non-default policy?

**Comment by kbrown** [comment]
I did this to get around it

/**
 * sets up react-cognito with default policies.
*/
const setupCognito = (store, config, listeners=[emailVerificationRequired, identityPoolLogin]) => {
  store.dispatch(Action.configure(config));
  listeners.forEach((f) => {
    enable(store,f);
  });
};

**Comment by dibell** [comment]
fixed in #7
