### ISSUE TITLE
Insufficient privilege error when logging in

### ISSUE THREAD

**Issue by mgalindo** [isotoma/react-cognito#22]
I am using you example code, when I try to login a user that is already verified I get the following error "Insufficient privilege".  
I can create new users and change password but not log in.

**Comment by egut** [comment]
I got the same issue for me it was both these issues:
- The Identity pool wasn't connected to the correct User Pool. (Check the IAM trusted relationships too)
   (Check if you get an http 400 error in the debug toolbar in the browser)
- In the code a cognito group were assigned to config that the user didn't belong to. Remove that code to add the user to that cognito group solved that for me.

**Comment by dibell** [comment]
config.group = 'admins' in index.js on the example code requires the user to be in a group called 'admins'. I've updated the example code to remove this and added a comment to clarify.
