### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by egut** [isotoma/react-cognito#24]
Hi

I get this warning: 
lowPriorityWarning.js:40 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

I assume its just changing from:

`import React, { PropTypes } from 'react';`

to:

`import React from 'react';
import PropTypes from 'prop-types';`

**Comment by dibell** [comment]
Merged. Release on it's way...
