### ISSUE TITLE
Example errors out with "Cannot read property 'connect' of undefined"

### ISSUE THREAD

**Issue by iguana** [isotoma/react-cognito#6]
I updated config.json, then I ran:
```bash
npm run examples
```

Then tried to serve examples/htdocs via static http.

```
bundle.js:106 Uncaught TypeError: Cannot read property 'connect' of undefined
    at bundle.js:106
    at bundle.js:10
    at bundle.js:13
```

**Comment by xiaobaiczq** [comment]
I have the same issue ,do you handle this problem?

**Comment by kellyjanderson** [comment]
Either react-redux is not installed or the code referencing connect did not import { connect } from 'react-redux'

**Comment by dibell** [comment]
examples moved to react-cognito-example
