### ISSUE TITLE
Feature Request: setupCognito - ability to enable different features without editing library

### ISSUE THREAD

**Issue by kbrown** [isotoma/react-cognito#7]
I'm having to modify policy.js or recreate setupCognito if I want a different behavior.  I'd like to be able to pass in the features to enable in an array.

const setupCognito = (store, config) => {
  store.dispatch(Action.configure(config));
  enable(store, direct);
  //enable(store, emailVerificationRequired);
  enable(store, identityPoolLogin);
};

**Comment by dibell** [comment]
merged
